import assert from 'node:assert/strict';
import { CINEMATIC_SHOT_PRESETS, createCinematicShot } from './cinematic-shot';

const line = [{ x: 0, y: 0 }, { x: 6000, y: 0 }];
const low = createCinematicShot('low-track', line);
assert.equal(low.cameraHeightM, 0.32);
assert.equal(low.lensMm, 24);
assert.equal(low.lookAt.kind, 'tangent');
assert.deepEqual(low.controlPoints, line);
assert.ok(low.path.totalDurationSec > 8);
assert.equal(low.safety.requiresSceneCollisionCheck, true);
const follow = createCinematicShot('follow', line);
assert.equal(follow.stabilization, 'handheld');
assert.equal(follow.path.samples.at(-1)?.point.x, 6000);
const target = { x: 3000, y: 2000 };
const reveal = createCinematicShot('reveal', line, { target });
assert.deepEqual(reveal.lookAt, { kind: 'point', at: target });
const push = createCinematicShot('push-in', line, { target, speedMmPerSec: 300 });
assert.ok(push.path.totalDurationSec > reveal.path.totalDurationSec);
const orbit = createCinematicShot('orbit', [], { target, orbitRadiusMm: 2000 });
assert.ok(orbit.controlPoints.length >= 7);
for (const p of orbit.controlPoints) assert.ok(Math.abs(Math.hypot(p.x - target.x, p.y - target.y) - 2000) < 1e-6);
assert.equal(orbit.lookAt.kind, 'point');
assert.throws(() => createCinematicShot('orbit', []), /cần một điểm nhấn/);
assert.throws(() => createCinematicShot('reveal', line), /cần một điểm nhấn/);
assert.equal(Object.keys(CINEMATIC_SHOT_PRESETS).length, 5);
const tiny = createCinematicShot('low-track', [{ x: 0, y: 0 }, { x: 100, y: 0 }]);
assert.ok(tiny.safety.warnings.some((w) => w.includes('quá ngắn')));
console.log('cinematic-shot: assertions passed');
