import { chromium } from 'playwright';
const out = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('console', m => { if (m.type() === 'error') errs.push(m.text().slice(0,300)); });
p.on('pageerror', e => errs.push('PAGEERROR: ' + String(e).slice(0,300)));
await p.goto('http://localhost:3001/', { waitUntil: 'networkidle', timeout: 90000 });
await p.waitForTimeout(3000);
await p.screenshot({ path: out, fullPage: false });
console.log('URL:', p.url());
console.log('TITLE:', await p.title());
console.log('ERRORS:', JSON.stringify(errs.slice(0,15), null, 1));
await b.close();
