'use client';

/**
 * components/cad/PlanPresentPanel.tsx — BẢNG ĐIỀU KHIỂN ỐNG KÍNH TRÌNH BÀY (phiên S4).
 *
 * §9 THIẾT KẾ TRƯỚC — TÍNH NĂNG FILL SAU: panel này vẽ ĐỦ cả những ô CHƯA code, mỗi ô `disabled`
 * **kèm lý do riêng tại chỗ**. ⛔ Cấm nút giả bấm không ra gì. Khuôn chép từ mẫu đúng đã có:
 * `components/render-studio/Command3DPanel.tsx:123-125` (docstring nêu lý do) + `:236-244`
 * (nút `disabled` thật — Tooltip + viền đứt). ⚠️ Số dòng `:113,139` mà phiếu cũ trỏ đã LỖI THỜI,
 * S5 đính chính 05/08. Mỗi ô mờ ở đây khớp 1-1 một dòng trong `docs/CHECKLIST-TONG.md`.
 *
 * ⛔ Panel KHÔNG tự chế màu/kích thước (L4). Bảng màu trình bày là tham số của
 * `lib/cad/plan-present.ts`; ở đây chỉ bật/tắt, không đặt hex nào.
 */

import { useState } from 'react';
import { Trees, Users, Circle, LayoutGrid, Tag, Layers, Image as ImageIcon, Palette, X } from 'lucide-react';
import { useT } from '@/lib/i18n';
import { cn } from '@/lib/utils';
import Tooltip from '@/components/ui/Tooltip';
import { useCadStore } from '@/lib/cad/store';
import { entityBox } from '@/lib/cad/model';
import { usePlanPresent } from './plan-present-store';
import {
  autoPlaceLeaders, leadersToEntities, leaderKey, leaderSeed,
  type LeaderRequest, type LeaderLayout,
} from '@/lib/cad/plan-leader';
import { BLOCK_MAP } from '@/lib/cad/furniture';
import { Checkpoint } from '@/components/studio/Checkpoint';
import type { CheckpointItem, CheckpointPhase } from '@/components/studio/checkpoint-core';
import { LeaderPreview } from './LeaderPreview';

/* ─────────── ô CHƯA CÓ — §9: hiện ra, mờ đi, nói rõ lý do ─────────── */
/**
 * Mỗi dòng = 1 ô trống trên giao diện = 1 dòng `CHECKLIST-TONG.md`. Lý do phải RIÊNG cho từng ô
 * (bài học `Command3DPanel`: dùng chung một câu "đợi X" là giấu mất sự thật khác nhau).
 */
const O_CHUA_CO: { id: string; vi: string; en: string; icon: typeof Layers; reason: [string, string] }[] = [
  {
    id: 'depth', vi: 'Phân lớp độ đậm', en: 'Depth layering', icon: Layers,
    reason: [
      'Chờ đường trích mặt đứng (S2). Phần tính toán đã xong (lib/cad/plan-depth.ts) — chưa màn nào sinh ra mặt đứng để tô.',
      'Waiting on the elevation extractor (S2). The maths is done (lib/cad/plan-depth.ts) — no screen produces an elevation to shade yet.',
    ],
  },
  {
    id: 'blockdecor', vi: 'Cây · người từ thư viện', en: 'Library plants · people', icon: Trees,
    reason: [
      'Cây và người hiện sinh bằng hàm. Bộ block cây/người thuộc thư viện khối (mảng S3) — nối xong sẽ thay được.',
      'Plants and people are currently generated by code. The plant/person block set belongs to the block library (S3) — swappable once it lands.',
    ],
  },
  {
    id: 'exportpng', vi: 'Xuất PNG bản trình bày', en: 'Export presentation PNG', icon: ImageIcon,
    reason: [
      'Đường xuất PNG hiện ép mọi nét về đen (render.ts renderDocToDataURL forceColor #111111) — xuất ra sẽ mất hết màu. Sửa chỗ đó nằm ngoài vùng phiên này.',
      'The PNG export path forces every stroke to black (render.ts renderDocToDataURL forceColor #111111) — colours would be lost. Fixing it is outside this session’s scope.',
    ],
  },
  {
    id: 'brandpalette', vi: 'Bảng màu theo studio', en: 'Studio palette', icon: Palette,
    reason: [
      'Chưa nối Brand Kit. Bảng màu đã là tham số truyền đè được (PresentOptions.palette) — chỉ thiếu màn chọn.',
      'Not wired to the Brand Kit yet. The palette is already an overridable parameter (PresentOptions.palette) — only the picker is missing.',
    ],
  },
];

/* Khuôn panel nổi — CHÉP NGUYÊN token của `components/cad/ZonePanel.tsx:21-40` (L4: không tự chế
   màu/kích thước). Ổ `left:12, top:70` đã bị ZonePanel chiếm (RevitSummaryPanel.tsx:21 ghi rõ),
   nên panel này neo MÉP PHẢI để không chồng. */
const panel: React.CSSProperties = {
  position: 'absolute',
  zIndex: 22,
  background: 'color-mix(in srgb, var(--panel) 92%, transparent)',
  backdropFilter: 'blur(14px)',
  WebkitBackdropFilter: 'blur(14px)', // K3: thiếu prefix = tablet không blur
  border: '1px solid var(--border)',
  borderRadius: 12,
  padding: 8,
  boxShadow: '0 8px 24px rgba(0,0,0,.18)',
};
const headStyle: React.CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  fontSize: 10.5, letterSpacing: '0.18em', textTransform: 'uppercase', fontWeight: 650,
  color: 'var(--t3)', padding: '2px 4px 8px',
};
const miniBtn: React.CSSProperties = {
  display: 'grid', placeItems: 'center', width: 22, height: 22, borderRadius: 6,
  border: 'none', background: 'transparent', color: 'var(--t3)', cursor: 'pointer',
};

export default function PlanPresentPanel({ onClose }: { onClose: () => void }) {
  const tr = useT();
  const st = usePlanPresent();
  const [msg, setMsg] = useState('');

  const say = (s: string) => { setMsg(s); setTimeout(() => setMsg(''), 3200); };

  /* ── VIỆC 2 — ghi nhãn leader cho vật thể ĐANG CHỌN, qua CHECKPOINT (§0e KS1–KS5) ──
     Leader là NỘI DUNG BẢN VẼ thật (khác trang trí phái sinh của chế độ trình bày: cái đó chỉ
     đổi cách vẽ, không sinh entity ⇒ theo phiếu S5 KHÔNG cần checkpoint). Vì nó GHI VÀO `Doc`
     nên phải đi qua khuôn duyệt: xem trước sản phẩm thật → tick từng nhãn → chỉ ghi cái đã tick.
     ⛔ Dùng `components/studio/Checkpoint.tsx` của S5, KHÔNG tự đẻ khuôn riêng. */
  const selection = useCadStore((s) => s.selection);
  const [phase, setPhase] = useState<CheckpointPhase>('idle');
  const [layout, setLayout] = useState<LeaderLayout | null>(null);
  const [items, setItems] = useState<CheckpointItem[]>([]);
  const [seed, setSeed] = useState<number | null>(null);
  const [undoLabel, setUndoLabel] = useState('');
  const [scaleN, setScaleN] = useState(100);

  /** Gom yêu cầu ghi nhãn từ selection. Nhãn theo K3: KHAI BÁO trước, không bịa tên. */
  const buildRequests = (): LeaderRequest[] => {
    const cad = useCadStore.getState();
    const reqs: LeaderRequest[] = [];
    for (const e of cad.doc.entities) {
      if (!cad.selection.includes(e.id)) continue;
      const label =
        (e.type === 'block' ? BLOCK_MAP[e.block]?.name : undefined) ??
        e.srcBlock ??
        (e.elementType ?? undefined);
      if (!label) continue;
      // điểm chỉ = tâm hình bao của CHÍNH entity — sinh bằng hàm, không gõ toạ độ tay
      const b = entityBox(e);
      if (!Number.isFinite(b.minX)) continue;
      reqs.push({ at: { x: (b.minX + b.maxX) / 2, y: (b.minY + b.maxY) / 2 }, label, id: e.id });
    }
    return reqs;
  };

  const chay = () => {
    const cad = useCadStore.getState();
    const reqs = buildRequests();
    if (!reqs.length) {
      say(tr('Vật thể đang chọn không có tên để ghi nhãn.', 'The selected objects have no name to label.'));
      return;
    }
    const k = cad.doc.printScale ?? 100;
    const lay = autoPlaceLeaders(reqs, { scaleN: k });
    setScaleN(k);
    setLayout(lay);
    setSeed(leaderSeed(reqs, { scaleN: k }));
    setUndoLabel(
      tr(
        `bản vẽ trước khi đặt nhãn (${cad.doc.entities.length} đối tượng)`,
        `the drawing before labelling (${cad.doc.entities.length} objects)`,
      ),
    );
    setItems(
      lay.placed.map((p, i) => ({
        id: leaderKey(p, i),
        label: p.label,
        // `detail` phải là SỐ THẬT, không phải câu mô tả (checkpoint-core.ts:33 docstring)
        detail: `${p.angleDeg}° · ${p.dir > 0 ? tr('sang phải', 'right') : tr('sang trái', 'left')}`,
        why: tr(
          `Góc ${p.angleDeg}° lấy từ tập góc chung 30/45/60°; hướng chọn ra xa tâm đám; không cắt leader nào đã đặt.`,
          `Angle ${p.angleDeg}° from the shared 30/45/60° set; direction points away from the cluster centre; crosses no already-placed leader.`,
        ),
        selected: true,
      })),
    );
    setPhase('preview');
  };

  const nhan = (ids: string[]) => {
    const cad = useCadStore.getState();
    if (!layout) return;
    // ⛔ CHỈ ghi phần đã tick — `only` chặn đường "ghi cả mẻ" (KS3).
    const ents = leadersToEntities(layout, {
      layer: cad.doc.layers.find((l) => /text|ghi|note/i.test(l.name))?.id ?? cad.doc.layers[0]?.id,
      style: { scaleN },
      idPrefix: `ld-${(seed ?? 0).toString(36)}`,
      only: ids,
    });
    cad.addEntities(ents);
    setPhase('idle');
    setLayout(null);
    say(tr(`Đã ghi ${ids.length} nhãn vào bản vẽ.`, `Wrote ${ids.length} leaders into the drawing.`));
  };

  const row = 'flex items-center justify-between gap-2 rounded-[9px] px-2 py-1.5 text-[11.5px] leading-[1.5]';
  const chip = (on: boolean) =>
    cn('rounded-[7px] border px-2 py-1 text-[10.5px] leading-[1.5] transition-colors',
      on ? 'border-[var(--accent)] bg-[var(--accent)]/12 text-[var(--accent)] font-semibold' : 'border-[var(--border)] text-[var(--t4)] hover:text-[var(--t2)]');

  return (
    <div style={{ ...panel, right: 12, top: 70, width: 272, maxHeight: 'calc(100% - 150px)', overflowY: 'auto' }} className="space-y-3">
      <div style={headStyle}>
        <span>{tr('Trình bày · Presentation', 'Presentation')}</span>
        <button type="button" onClick={onClose} style={miniBtn} title={tr('Đóng', 'Close')}>
          <X size={14} />
        </button>
      </div>

      {/* ── công tắc chính ── */}
      <button
        type="button"
        onClick={st.toggle}
        aria-pressed={st.on}
        className={cn(
          'flex w-full items-center justify-between rounded-[9px] border px-2.5 py-2 text-[12px] leading-[1.5] transition-colors',
          st.on
            ? 'border-[var(--accent)] bg-[var(--accent)]/12 font-semibold text-[var(--accent)]'
            : 'border-[var(--border)] text-[var(--t2)] hover:border-[var(--t4)]',
        )}
      >
        <span className="flex items-center gap-2"><LayoutGrid size={14} />{tr('Chế độ trình bày', 'Presentation mode')}</span>
        <span className="text-[10.5px] font-normal text-[var(--t4)]">{st.on ? tr('BẬT', 'ON') : tr('TẮT', 'OFF')}</span>
      </button>
      <p className="px-0.5 text-[10.5px] leading-[1.5] text-[var(--t4)]">
        {tr(
          'Cùng một bản vẽ, đổi cách hiển thị. Không đổi kích thước, không đổi vị trí, không tạo file thứ hai.',
          'Same drawing, different lens. Nothing is resized, nothing is moved, no second file is created.',
        )}
      </p>

      {/* ── tuỳ chọn ống kính ── */}
      <div className={cn('space-y-1 transition-opacity', st.on ? 'opacity-100' : 'pointer-events-none opacity-40')}>
        <div className={row}>
          <span className="text-[var(--t3)]">{tr('Nền', 'Ground')}</span>
          <div className="flex gap-1">
            <button type="button" className={chip(st.ground === 'flat')} onClick={() => st.set({ ground: 'flat' })}>{tr('Phẳng', 'Flat')}</button>
            <button type="button" className={chip(st.ground === 'islands')} onClick={() => st.set({ ground: 'islands' })}>{tr('Đảo', 'Islands')}</button>
            <button type="button" className={chip(st.ground === 'none')} onClick={() => st.set({ ground: 'none' })}>{tr('Không', 'None')}</button>
          </div>
        </div>
        <div className={row}>
          <span className="flex items-center gap-1.5 text-[var(--t3)]"><Circle size={12} />{tr('Thảm định vùng', 'Zoning rugs')}</span>
          <button type="button" className={chip(st.showRugs)} onClick={() => st.set({ showRugs: !st.showRugs })}>{st.showRugs ? tr('Hiện', 'On') : tr('Ẩn', 'Off')}</button>
        </div>
        <div className={row}>
          <span className="flex items-center gap-1.5 text-[var(--t3)]"><Trees size={12} />{tr('Cây xanh', 'Planting')}</span>
          <button type="button" className={chip(st.showPlants)} onClick={() => st.set({ showPlants: !st.showPlants })}>{st.showPlants ? tr('Hiện', 'On') : tr('Ẩn', 'Off')}</button>
        </div>
        <div className={row}>
          <span className="flex items-center gap-1.5 text-[var(--t3)]"><Users size={12} />{tr('Người', 'People')}</span>
          <button type="button" className={chip(st.showPeople)} onClick={() => st.set({ showPeople: !st.showPeople })}>{st.showPeople ? tr('Hiện', 'On') : tr('Ẩn', 'Off')}</button>
        </div>
      </div>

      {/* ── VIỆC 2 — leader ── */}
      <div className="space-y-1.5 border-t border-[var(--border)] pt-3">
        <p className="px-0.5 text-[9px] font-bold uppercase leading-[1.5] tracking-wide text-[var(--t4)]">
          {tr('Ghi nhãn', 'Annotation')}
        </p>
        <Tooltip
          side="right"
          label={selection.length
            ? tr('Đặt leader nét mảnh, nghiêng 30–60°, không mũi tên, tự tránh cắt nhau (ISO 128-22).', 'Places thin leaders at 30–60°, no arrowheads, auto non-crossing (ISO 128-22).')
            : tr('Chọn vật thể cần ghi nhãn trước.', 'Select the objects to label first.')}
        >
          <button
            type="button"
            disabled={!selection.length}
            onClick={chay}
            className={cn(
              'flex w-full items-center gap-2 rounded-[9px] border px-2.5 py-2 text-[11.5px] leading-[1.5] transition-colors',
              selection.length
                ? 'border-[var(--border)] text-[var(--t2)] hover:border-[var(--accent)] hover:text-[var(--accent)]'
                : 'cursor-not-allowed border-dashed border-[var(--border)] text-[var(--t5)]',
            )}
          >
            <Tag size={13} />
            {tr('Đặt nhãn leader cho vật thể đang chọn', 'Leader-label the current selection')}
          </button>
        </Tooltip>

        {/* ── khuôn duyệt của S5 — xem sản phẩm thật RỒI mới quyết, tick từng nhãn ── */}
        {layout && (
          <Checkpoint
            phase={phase}
            title={tr('Đặt nhãn leader', 'Place leader labels')}
            preview={<LeaderPreview layout={layout} selected={items.filter((i) => i.selected).map((i) => i.id)} />}
            items={items}
            onItemsChange={setItems}
            params={[
              { label: tr('Tỉ lệ in', 'Print scale'), value: `1:${scaleN}` },
              { label: tr('Tập góc', 'Angle set'), value: '30° · 45° · 60°' },
              { label: tr('Landing', 'Landing'), value: tr('20 × bề dày nét', '20 × line width') },
              {
                label: tr('Không đặt được', 'Could not place'),
                // N5 — khai thật, không giấu số nhãn bị bỏ
                value: layout.unplaced.length
                  ? tr(`${layout.unplaced.length} nhãn (sẽ cắt dây khác)`, `${layout.unplaced.length} (would cross another leader)`)
                  : tr('không có', 'none'),
              },
            ]}
            seed={seed}
            undoLabel={undoLabel}
            onAccept={nhan}
            onRetry={chay}
          />
        )}
      </div>

      {/* ── VIỆC 4 · §9 — ô CHƯA CÓ, hiện ra kèm lý do, KHÔNG ẩn cho gọn mắt ── */}
      <div className="space-y-1.5 border-t border-[var(--border)] pt-3">
        <p className="px-0.5 text-[9px] font-bold uppercase leading-[1.5] tracking-wide text-[var(--t4)]">
          {tr('Chưa làm được', 'Not available yet')}
        </p>
        {O_CHUA_CO.map((o) => {
          const Icon = o.icon;
          return (
            <Tooltip key={o.id} side="right" label={tr(o.reason[0], o.reason[1])}>
              <button
                type="button"
                disabled
                className="flex w-full cursor-not-allowed items-center gap-2 rounded-[9px] border border-dashed border-[var(--border)] px-2.5 py-2 text-[11.5px] leading-[1.5] text-[var(--t5)]"
              >
                <Icon size={13} />
                {tr(o.vi, o.en)}
              </button>
            </Tooltip>
          );
        })}
      </div>

      {msg && <p className="px-0.5 text-[10.5px] leading-[1.5] text-[var(--t3)]">{msg}</p>}
    </div>
  );
}
