/**
 * lib/cad/standards/intl-occupant-load.ts — Hệ số tính occupant load (số người/diện tích) theo
 * IBC 2021 Table 1004.5 (Maximum Floor Area Allowances Per Occupant), đối chiếu chéo NFPA 101
 * Table 7.3.1.2 — 2 bộ quy chuẩn ĐỘC LẬP cho ra số khớp nhau ở HẦU HẾT hạng mục.
 *
 * Đơn vị gốc là sqft/người, đã quy đổi sẵn sang m²/người (1 sqft = 0.092903 m²) — dùng ĐÚNG các
 * số đã quy đổi trong params.m2PerOccupant, không tự tính lại.
 *
 * `params.areaBasisGross` phân biệt cách tính diện tích: 1 = 'gross' (diện tích sàn tổng, gồm cả
 * tường/hành lang/khu phụ), 0 = 'net' (diện tích sử dụng thực, trừ tường/cột) — StandardRule.params
 * chỉ nhận number (xem registry.ts) nên field boolean-như này mã hoá 1/0, ý nghĩa gross/net ghi rõ
 * trong `description`.
 *
 * Rule 'business-general' CỐ Ý verified=false: 2 nguồn mâu thuẫn nhau (100 sqft/người ≈9.29 m² vs
 * 150 sqft/người ≈13.94 m²) — KHÔNG tự chọn 1 số, giữ dải m2PerOccupantLow/High + note yêu cầu đối
 * chiếu bản gốc IBC 2021 Table 1004.5 dòng "Business areas" trước khi dùng chính thức.
 */
import type { RuleGroup } from './registry';

const SOURCE = 'IBC 2021 Table 1004.5 (Occupant Load Factor), đối chiếu NFPA 101 Table 7.3.1.2';

export const INTL_OCCUPANT_LOAD: RuleGroup = {
  id: 'intl-occupant-load',
  name: 'Occupant Load (IBC 2021 Table 1004.5 / NFPA 101 Table 7.3.1.2)',
  rules: [
    {
      id: 'intl-occupant-load-assembly-standing',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Assembly – khu vực đứng (concentrated, standing space): 0.46 m²/người (net — diện tích sử dụng thực, trừ tường/cột).',
      params: { m2PerOccupant: 0.46, areaBasisGross: 0 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-assembly-unconcentrated',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Assembly – ghế rời tập trung (unconcentrated, chairs only – not fixed): 0.65 m²/người (net).',
      params: { m2PerOccupant: 0.65, areaBasisGross: 0 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-assembly-tables-chairs',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Assembly – bàn & ghế (tables and chairs): 1.39 m²/người (net).',
      params: { m2PerOccupant: 1.39, areaBasisGross: 0 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-business-general',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Business – khu vực chung (văn phòng, general business areas): dải 9.29–13.94 m²/người (gross) — MÂU THUẪN giữa 2 nguồn (100 sqft/người vs 150 sqft/người), KHÔNG dùng 1 số cụ thể cho tới khi đối chiếu bản gốc.',
      params: { m2PerOccupantLow: 9.29, m2PerOccupantHigh: 13.94, areaBasisGross: 1 },
      verified: false,
      note: 'MÂU THUẪN GIỮA 2 NGUỒN: 1 nguồn ghi 100 sqft/người (≈9.29 m²), nguồn khác ghi 150 sqft/người (≈13.94 m²) cho "Business areas". Cần đối chiếu IBC 2021 Table 1004.5 bản gốc dòng "Business areas" (và bản NFPA 101 Table 7.3.1.2 tương ứng) trước khi dùng cho hồ sơ chính thức — KHÔNG tự chọn 1 trong 2 số.',
    },
    {
      id: 'intl-occupant-load-business-concentrated',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Business – tập trung (call center, business areas – concentrated): 4.65 m²/người (gross).',
      params: { m2PerOccupant: 4.65, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-educational-classroom',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Educational – lớp học (classroom): 1.86 m²/người (net).',
      params: { m2PerOccupant: 1.86, areaBasisGross: 0 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-educational-shop-lab',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Educational – xưởng/phòng thực hành (shops and other vocational room areas): 4.65 m²/người (net).',
      params: { m2PerOccupant: 4.65, areaBasisGross: 0 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-mercantile-ground-basement',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Mercantile – tầng trệt/tầng hầm (basement and grade floor areas): 2.79 m²/người (gross).',
      params: { m2PerOccupant: 2.79, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-mercantile-upper-floors',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Mercantile – các tầng trên (areas on other floors): 5.57 m²/người (gross).',
      params: { m2PerOccupant: 5.57, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-mercantile-storage',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Mercantile – khu kho (storage, stock, shipping areas): 27.87 m²/người (gross).',
      params: { m2PerOccupant: 27.87, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-residential',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Residential – khách sạn/căn hộ (residential): 18.58 m²/người (gross).',
      params: { m2PerOccupant: 18.58, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này. Rule DUY NHẤT trong nhóm này được nối đo tự động (info-only, ước tính) cho room kind "living" trong checker.ts — vì đây là loại duy nhất khớp với 1 room kind mà classifyRoom() đã phân loại trong InteriorFlow.',
    },
    {
      id: 'intl-occupant-load-institutional-sleeping',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Institutional – khu ngủ (sleeping areas): 11.15 m²/người (gross).',
      params: { m2PerOccupant: 11.15, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-institutional-inpatient',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Institutional – khu điều trị nội trú (inpatient treatment areas): 22.30 m²/người (gross).',
      params: { m2PerOccupant: 22.30, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-industrial',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Industrial areas: 9.29 m²/người (gross).',
      params: { m2PerOccupant: 9.29, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-storage-ordinary',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Storage – kho thường (warehouses – storage occupancies): 46.45 m²/người (gross).',
      params: { m2PerOccupant: 46.45, areaBasisGross: 1 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
    {
      id: 'intl-occupant-load-day-care',
      source: SOURCE,
      category: 'egress',
      severity: 'info',
      region: 'US',
      binding: 'mandatory',
      description: 'Day-care (nhà trẻ): 3.25 m²/người (net).',
      params: { m2PerOccupant: 3.25, areaBasisGross: 0 },
      verified: true,
      note: 'Xác nhận qua IBC 2021 Table 1004.5, đối chiếu NFPA 101 Table 7.3.1.2. 2 nguồn khớp nhau ở hạng mục này.',
    },
  ],
};
